sudo: required
language: go
services:
- docker
go:
- 1.9.x
install:
- set -e
- curl -fsSLo "$GOPATH/bin/dep" "https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64"
- bin/vendor
script:
- test -z "$(bin/format | tee >(cat >&2))"
- bin/test -nodes=2 -compilers=2
