required = [
  # Utilities
  "github.com/onsi/ginkgo/ginkgo",
  "github.com/golang/mock/mockgen",
]

ignored = [
  "code.cloudfoundry.org/cli/*",
  "github.com/docker/docker/*",
]

# Library

[[constraint]]
  name = "github.com/nu7hatch/gouuid"
  branch = "master"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

# Test

[[constraint]]
  name = "github.com/onsi/ginkgo"
  branch = "master"

[[constraint]]
  name = "github.com/onsi/gomega"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
